import type { ErrorCode, OrderStatus, OrderType } from '@resto/shared';

// UI copy of the guest menu. Restaurant content (dishes, categories) comes
// from the database; only the interface texts live here.
const fr = {
  table: 'Table',
  search: 'Rechercher un plat',
  searchClear: 'Effacer',
  noResults: 'Aucun résultat',
  soldOut: 'Épuisé',
  add: 'Ajouter',
  addToCart: 'Ajouter',
  choose: 'Choisissez une option',
  quantity: 'Quantité',
  itemNote: 'Une précision ? (sans oignons, bien cuit...)',
  viewCart: 'Voir le panier',
  items: (n: number) => (n === 1 ? '1 article' : `${n} articles`),
  cart: 'Votre commande',
  emptyCart: 'Votre panier est vide',
  orderNote: 'Note pour la cuisine',
  orderNotePh: 'Allergies, demandes particulières...',
  orderType: { dine_in: 'Sur place', takeaway: 'À emporter', delivery: 'Livraison' } as Record<OrderType, string>,
  name: 'Prénom',
  phone: 'Téléphone',
  address: 'Adresse de livraison',
  total: 'Total',
  placeOrder: 'Commander',
  sending: 'Envoi...',
  scanTable: 'Scannez le QR code sur votre table pour commander.',
  orderingOff: 'La commande en ligne est momentanément indisponible. Le menu reste consultable.',
  browseOnly: 'Menu en consultation',
  when: 'Quand ?',
  asap: 'Dès que possible',
  later: 'Plus tard',
  ready: (m: number) => 'Prête en {m} min environ'.replace('{m}', String(m)),
  closedNow: 'Fermé en ce moment : commandez pour plus tard.',
  closedNoSchedule: 'Fermé en ce moment. Revenez pendant nos horaires.',
  pausedNow: (h: string) => 'Commandes en ligne en pause jusqu’à {h}.'.replace('{h}', h),
  deliveryFee: 'Livraison',
  free: 'Offerte',
  freeFrom: (m: string) => 'Livraison offerte dès {m}'.replace('{m}', m),
  minOrder: (m: string) => 'Minimum {m} pour la livraison'.replace('{m}', m),
  area: 'Zone de livraison :',
  shareLocation: 'Partager ma position (pour le livreur)',
  locationShared: 'Position partagée ✓',
  locationFail: 'Position indisponible, l’adresse suffit.',
  readyAround: (h: string) => 'Prête vers {h}'.replace('{h}', h),
  deliveredAround: (h: string) => 'Livraison vers {h}'.replace('{h}', h),
  askedFor: (h: string) => 'Pour {h}'.replace('{h}', h),
  waitingConfirm: 'En attente de confirmation du restaurant…',
  contactWhatsApp: 'Écrire au restaurant sur WhatsApp',
  payOnPickup: 'Paiement au retrait.',
  payOnDelivery: 'Paiement à la livraison.',
  noCommission: 'Commande directe, sans commission',
  orderOnline: 'Commander en ligne',
  subtotal: 'Sous-total',
  thanks: 'Merci ! Commande reçue',
  ticket: 'Commande',
  status: {
    new: 'Reçue', preparing: 'En préparation', ready: 'Prête', served: 'Servie', cancelled: 'Annulée',
  } as Record<OrderStatus, string>,
  statusHint: {
    new: 'Le restaurant a bien reçu votre commande.',
    preparing: 'La cuisine s’en occupe.',
    ready: 'Votre commande est prête.',
    served: 'Bon appétit !',
    cancelled: 'Cette commande a été annulée. Adressez-vous au personnel.',
  } as Record<OrderStatus, string>,
  payAtCounter: 'Le paiement se fait auprès du personnel.',
  backToMenu: 'Retour au menu',
  trackOrder: 'Suivre',
  notFound: 'Restaurant introuvable',
  notFoundHint: 'Vérifiez le lien ou scannez à nouveau le QR code.',
  retry: 'Réessayer',
  loadError: 'Impossible de charger le menu.',
  close: 'Fermer',
  remove: 'Retirer',
  poweredBy: 'Propulsé par',
  reviewCta: 'Laissez-nous un avis Google',
  pickExactly: (n: number) => 'Choisissez {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'Au moins {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'Jusqu’à {n}'.replace('{n}', String(n)),
  optional: 'Facultatif',
  reviewHint: 'Vous avez aimé ? Votre avis nous aide énormément.',
  featured: 'Nos incontournables',
  from: 'dès',
  welcome: 'Bienvenue',
  happyHour: (pct: string, until: string) => `Happy hour : -${pct} %${until ? ` jusqu’à ${until}` : ''}`,
  promoCode: 'Code promo',
  kioskName: 'Votre prénom (pour vous appeler)',
  kioskNumber: 'Votre numéro',
  kioskPay: 'Payez à la caisse en donnant ce numéro.',
  kioskNew: 'Nouvelle commande',
  apply: 'Appliquer',
  promoApplied: (name: string) => `Code « ${name} » appliqué`,
  discount: 'Réduction',
  tags: { popular: 'Populaire', spicy: 'Épicé', new: 'Nouveau', vegetarian: 'Végétarien' } as Record<string, string>,
  errors: {
    restaurant_not_found: 'Restaurant introuvable.',
    ordering_unavailable: 'La commande en ligne est indisponible pour le moment.',
    qr_ordering_off: 'Ce menu est à consulter : commandez auprès du serveur.',
    order_type_unavailable: 'Ce mode de commande n’est pas disponible.',
    invalid_table: 'Ce QR code de table n’est plus valide. Demandez au personnel.',
    customer_required: 'Merci d’indiquer votre prénom et votre téléphone.',
    item_unavailable: 'Un article n’est plus disponible, il a été retiré du panier.',
    item_sold_out: 'Un article est épuisé, il a été retiré du panier.',
    variant_required: 'Choisissez une option pour chaque article.',
    rate_limited: 'Trop de commandes en peu de temps. Réessayez dans quelques minutes.',
    invalid_request: 'La commande n’a pas pu être envoyée. Vérifiez votre panier.',
    network: 'Pas de connexion. Votre panier est conservé, réessayez.',
    closed: 'Le restaurant est fermé à cette heure. Choisissez un autre moment.',
    online_paused: 'Les commandes en ligne sont en pause pour quelques minutes.',
    below_minimum: 'Le minimum pour la livraison n’est pas atteint.',
    promo_invalid: 'Ce code n’existe pas ou n’est pas valable maintenant.',
    promo_minimum: 'Votre commande n’atteint pas le minimum de ce code.',
    promo_used_up: 'Ce code a déjà été utilisé le nombre maximum de fois.',
    promo_already_used: 'Vous avez déjà utilisé ce code.',
    promo_phone_required: 'Indiquez votre téléphone pour utiliser ce code.',
  } as Record<ErrorCode, string>,
};

type Strings = typeof fr;

const en: Strings = {
  ...fr,
  table: 'Table',
  search: 'Search the menu',
  searchClear: 'Clear',
  noResults: 'No results',
  soldOut: 'Sold out',
  add: 'Add',
  addToCart: 'Add',
  choose: 'Choose an option',
  quantity: 'Quantity',
  itemNote: 'Any special request? (no onions, well done...)',
  viewCart: 'View order',
  items: (n: number) => (n === 1 ? '1 item' : `${n} items`),
  cart: 'Your order',
  emptyCart: 'Your order is empty',
  orderNote: 'Note for the kitchen',
  orderNotePh: 'Allergies, special requests...',
  orderType: { dine_in: 'Dine in', takeaway: 'Takeaway', delivery: 'Delivery' },
  name: 'First name',
  phone: 'Phone',
  address: 'Delivery address',
  total: 'Total',
  placeOrder: 'Place order',
  sending: 'Sending...',
  scanTable: 'Scan the QR code on your table to order.',
  orderingOff: 'Online ordering is temporarily unavailable. You can still browse the menu.',
  browseOnly: 'Browse only',
  when: 'When?',
  asap: 'As soon as possible',
  later: 'Later',
  ready: (m: number) => 'Ready in about {m} min'.replace('{m}', String(m)),
  closedNow: 'Closed right now: order for later.',
  closedNoSchedule: 'Closed right now. Come back during opening hours.',
  pausedNow: (h: string) => 'Online orders paused until {h}.'.replace('{h}', h),
  deliveryFee: 'Delivery',
  free: 'Free',
  freeFrom: (m: string) => 'Free delivery from {m}'.replace('{m}', m),
  minOrder: (m: string) => 'Minimum {m} for delivery'.replace('{m}', m),
  area: 'Delivery area:',
  shareLocation: 'Share my location (for the rider)',
  locationShared: 'Location shared ✓',
  locationFail: 'Location unavailable, the address is enough.',
  readyAround: (h: string) => 'Ready around {h}'.replace('{h}', h),
  deliveredAround: (h: string) => 'Delivery around {h}'.replace('{h}', h),
  askedFor: (h: string) => 'For {h}'.replace('{h}', h),
  waitingConfirm: 'Waiting for the restaurant to confirm…',
  contactWhatsApp: 'Message the restaurant on WhatsApp',
  payOnPickup: 'Pay when you pick up.',
  payOnDelivery: 'Pay on delivery.',
  noCommission: 'Order direct, no commission',
  orderOnline: 'Order online',
  subtotal: 'Subtotal',
  thanks: 'Thank you! Order received',
  ticket: 'Order',
  status: { new: 'Received', preparing: 'Preparing', ready: 'Ready', served: 'Served', cancelled: 'Cancelled' },
  statusHint: {
    new: 'The restaurant has received your order.',
    preparing: 'The kitchen is on it.',
    ready: 'Your order is ready.',
    served: 'Enjoy your meal!',
    cancelled: 'This order was cancelled. Please ask the staff.',
  },
  payAtCounter: 'Payment is handled by the staff.',
  backToMenu: 'Back to menu',
  trackOrder: 'Track',
  notFound: 'Restaurant not found',
  notFoundHint: 'Check the link or scan the QR code again.',
  retry: 'Try again',
  loadError: 'Could not load the menu.',
  close: 'Close',
  remove: 'Remove',
  poweredBy: 'Powered by',
  reviewCta: 'Leave us a Google review',
  pickExactly: (n: number) => 'Choose {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'At least {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'Up to {n}'.replace('{n}', String(n)),
  optional: 'Optional',
  reviewHint: 'Enjoyed it? Your review helps us a lot.',
  featured: 'Must try',
  from: 'from',
  welcome: 'Welcome',
  happyHour: (pct: string, until: string) => `Happy hour: -${pct}%${until ? ` until ${until}` : ''}`,
  promoCode: 'Promo code',
  kioskName: 'Your first name (to call you)',
  kioskNumber: 'Your number',
  kioskPay: 'Pay at the counter with this number.',
  kioskNew: 'New order',
  apply: 'Apply',
  promoApplied: (name: string) => `Code “${name}” applied`,
  discount: 'Discount',
  tags: { popular: 'Popular', spicy: 'Spicy', new: 'New', vegetarian: 'Vegetarian' },
  errors: {
    restaurant_not_found: 'Restaurant not found.',
    ordering_unavailable: 'Online ordering is unavailable right now.',
    qr_ordering_off: 'This menu is to read: please order with the staff.',
    order_type_unavailable: 'This order type is not available.',
    invalid_table: 'This table QR code is no longer valid. Please ask the staff.',
    customer_required: 'Please enter your first name and phone number.',
    item_unavailable: 'An item is no longer available and was removed from your order.',
    item_sold_out: 'An item is sold out and was removed from your order.',
    variant_required: 'Please choose an option for each item.',
    rate_limited: 'Too many orders in a short time. Please try again in a few minutes.',
    invalid_request: 'The order could not be sent. Please check your order.',
    network: 'No connection. Your order is kept, please try again.',
    closed: 'The restaurant is closed at that time. Pick another time.',
    online_paused: 'Online orders are paused for a few minutes.',
    below_minimum: 'The delivery minimum is not reached.',
    promo_invalid: 'This code does not exist or is not valid right now.',
    promo_minimum: 'Your order does not reach the minimum for this code.',
    promo_used_up: 'This code has reached its maximum number of uses.',
    promo_already_used: 'You have already used this code.',
    promo_phone_required: 'Enter your phone number to use this code.',
  },
};

const ar: Strings = {
  ...fr,
  table: 'الطاولة',
  search: 'ابحث في القائمة',
  searchClear: 'مسح',
  noResults: 'لا توجد نتائج',
  soldOut: 'نفد',
  add: 'أضف',
  addToCart: 'أضف',
  choose: 'اختر خيارا',
  quantity: 'الكمية',
  itemNote: 'طلب خاص؟ (بدون بصل، مطهو جيدا...)',
  viewCart: 'عرض الطلب',
  items: (n: number) => (n === 1 ? 'منتج واحد' : `${n} منتجات`),
  cart: 'طلبك',
  emptyCart: 'طلبك فارغ',
  orderNote: 'ملاحظة للمطبخ',
  orderNotePh: 'حساسية، طلبات خاصة...',
  orderType: { dine_in: 'في المطعم', takeaway: 'للأخذ', delivery: 'توصيل' },
  name: 'الاسم',
  phone: 'الهاتف',
  address: 'عنوان التوصيل',
  total: 'المجموع',
  placeOrder: 'اطلب الآن',
  sending: 'جار الإرسال...',
  scanTable: 'امسح رمز QR الموجود على طاولتك للطلب.',
  orderingOff: 'الطلب عبر الإنترنت غير متاح حاليا. يمكنك تصفح القائمة.',
  browseOnly: 'تصفح فقط',
  when: 'متى؟',
  asap: 'في أقرب وقت',
  later: 'لاحقا',
  ready: (m: number) => 'جاهزة في حوالي {m} دقيقة'.replace('{m}', String(m)),
  closedNow: 'مغلق الآن: اطلبوا لوقت لاحق.',
  closedNoSchedule: 'مغلق الآن. عودوا خلال أوقات العمل.',
  pausedNow: (h: string) => 'الطلبات عبر الإنترنت متوقفة حتى {h}.'.replace('{h}', h),
  deliveryFee: 'التوصيل',
  free: 'مجاني',
  freeFrom: (m: string) => 'توصيل مجاني ابتداء من {m}'.replace('{m}', m),
  minOrder: (m: string) => 'الحد الأدنى {m} للتوصيل'.replace('{m}', m),
  area: 'منطقة التوصيل:',
  shareLocation: 'مشاركة موقعي (لعامل التوصيل)',
  locationShared: 'تمت مشاركة الموقع ✓',
  locationFail: 'الموقع غير متاح، العنوان يكفي.',
  readyAround: (h: string) => 'جاهزة حوالي {h}'.replace('{h}', h),
  deliveredAround: (h: string) => 'التوصيل حوالي {h}'.replace('{h}', h),
  askedFor: (h: string) => 'لـ {h}'.replace('{h}', h),
  waitingConfirm: 'في انتظار تأكيد المطعم…',
  contactWhatsApp: 'راسلوا المطعم عبر واتساب',
  payOnPickup: 'الدفع عند الاستلام.',
  payOnDelivery: 'الدفع عند التوصيل.',
  noCommission: 'طلب مباشر، بدون عمولة',
  orderOnline: 'اطلبوا عبر الإنترنت',
  subtotal: 'المجموع الفرعي',
  thanks: 'شكرا! تم استلام طلبك',
  ticket: 'الطلب',
  status: { new: 'تم الاستلام', preparing: 'قيد التحضير', ready: 'جاهز', served: 'تم التقديم', cancelled: 'ملغى' },
  statusHint: {
    new: 'تم استلام طلبك من طرف المطعم.',
    preparing: 'المطبخ يحضر طلبك.',
    ready: 'طلبك جاهز.',
    served: 'بالصحة والعافية!',
    cancelled: 'تم إلغاء هذا الطلب. يرجى التوجه إلى الموظفين.',
  },
  payAtCounter: 'الدفع يتم لدى الموظفين.',
  backToMenu: 'العودة إلى القائمة',
  trackOrder: 'تتبع',
  notFound: 'المطعم غير موجود',
  notFoundHint: 'تحقق من الرابط أو امسح رمز QR مرة أخرى.',
  retry: 'إعادة المحاولة',
  loadError: 'تعذر تحميل القائمة.',
  close: 'إغلاق',
  remove: 'حذف',
  poweredBy: 'بدعم من',
  reviewCta: 'اتركوا لنا رأيكم على Google',
  pickExactly: (n: number) => 'اختاروا {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'على الأقل {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'حتى {n}'.replace('{n}', String(n)),
  optional: 'اختياري',
  reviewHint: 'أعجبكم؟ رأيكم يساعدنا كثيرا.',
  featured: 'الأكثر طلبا',
  from: 'ابتداء من',
  welcome: 'مرحبا بكم',
  happyHour: (pct: string, until: string) => `ساعة التخفيض: ‎-${pct}%${until ? ` حتى ${until}` : ''}`,
  promoCode: 'رمز التخفيض',
  kioskName: 'اسمك (لمناداتك)',
  kioskNumber: 'رقمك',
  kioskPay: 'ادفع في الصندوق بهذا الرقم.',
  kioskNew: 'طلب جديد',
  apply: 'تطبيق',
  promoApplied: (name: string) => `تم تطبيق الرمز «${name}»`,
  discount: 'تخفيض',
  tags: { popular: 'الأكثر طلبا', spicy: 'حار', new: 'جديد', vegetarian: 'نباتي' },
  errors: {
    restaurant_not_found: 'المطعم غير موجود.',
    ordering_unavailable: 'الطلب عبر الإنترنت غير متاح حاليا.',
    qr_ordering_off: 'هذه القائمة للاطلاع: اطلبوا من النادل.',
    order_type_unavailable: 'طريقة الطلب هذه غير متاحة.',
    invalid_table: 'رمز الطاولة لم يعد صالحا. يرجى سؤال الموظفين.',
    customer_required: 'يرجى إدخال الاسم ورقم الهاتف.',
    item_unavailable: 'منتج لم يعد متوفرا وتم حذفه من طلبك.',
    item_sold_out: 'منتج نفد وتم حذفه من طلبك.',
    variant_required: 'يرجى اختيار خيار لكل منتج.',
    rate_limited: 'طلبات كثيرة في وقت قصير. حاول بعد بضع دقائق.',
    invalid_request: 'تعذر إرسال الطلب. تحقق من طلبك.',
    network: 'لا يوجد اتصال. طلبك محفوظ، حاول مرة أخرى.',
    closed: 'المطعم مغلق في هذا الوقت. اختاروا وقتا آخر.',
    online_paused: 'الطلبات عبر الإنترنت متوقفة لبضع دقائق.',
    below_minimum: 'لم يتم بلوغ الحد الأدنى للتوصيل.',
    promo_invalid: 'هذا الرمز غير موجود أو غير صالح الآن.',
    promo_minimum: 'طلبك لم يبلغ الحد الأدنى لهذا الرمز.',
    promo_used_up: 'تم استعمال هذا الرمز الحد الأقصى من المرات.',
    promo_already_used: 'سبق لك استعمال هذا الرمز.',
    promo_phone_required: 'أدخل رقم هاتفك لاستعمال هذا الرمز.',
  },
};

const ALL: Record<string, Strings> = { fr, en, ar };
export const strings = (lang: string): Strings => ALL[lang] ?? fr;
export const LANG_LABEL: Record<string, string> = { fr: 'FR', en: 'EN', ar: 'ع', es: 'ES' };
export type { Strings };
