import type { ErrorCode, OrderStatus, OrderType } from '@resto/shared';

// UI copy of the guest menu. Restaurant content (dishes, categories) comes
// from the database; only the interface texts live here.
const fr = {
  table: 'Table',
  search: 'Rechercher un plat',
  searchClear: 'Effacer',
  noResults: 'Aucun résultat',
  soldOut: 'Épuisé',
  add: 'Ajouter',
  addToCart: 'Ajouter',
  choose: 'Choisissez une option',
  quantity: 'Quantité',
  itemNote: 'Une précision ? (sans oignons, bien cuit...)',
  viewCart: 'Voir le panier',
  items: (n: number) => (n === 1 ? '1 article' : `${n} articles`),
  cart: 'Votre commande',
  emptyCart: 'Votre panier est vide',
  orderNote: 'Note pour la cuisine',
  orderNotePh: 'Allergies, demandes particulières...',
  orderType: { dine_in: 'Sur place', takeaway: 'À emporter', delivery: 'Livraison' } as Record<OrderType, string>,
  name: 'Prénom',
  phone: 'Téléphone',
  address: 'Adresse de livraison',
  total: 'Total',
  placeOrder: 'Commander',
  sending: 'Envoi...',
  scanTable: 'Scannez le QR code sur votre table pour commander.',
  orderingOff: 'La commande en ligne est momentanément indisponible. Le menu reste consultable.',
  browseOnly: 'Menu en consultation',
  thanks: 'Merci ! Commande reçue',
  ticket: 'Commande',
  status: {
    new: 'Reçue', preparing: 'En préparation', ready: 'Prête', served: 'Servie', cancelled: 'Annulée',
  } as Record<OrderStatus, string>,
  statusHint: {
    new: 'Le restaurant a bien reçu votre commande.',
    preparing: 'La cuisine s’en occupe.',
    ready: 'Votre commande est prête.',
    served: 'Bon appétit !',
    cancelled: 'Cette commande a été annulée. Adressez-vous au personnel.',
  } as Record<OrderStatus, string>,
  payAtCounter: 'Le paiement se fait auprès du personnel.',
  backToMenu: 'Retour au menu',
  trackOrder: 'Suivre',
  notFound: 'Restaurant introuvable',
  notFoundHint: 'Vérifiez le lien ou scannez à nouveau le QR code.',
  retry: 'Réessayer',
  loadError: 'Impossible de charger le menu.',
  close: 'Fermer',
  remove: 'Retirer',
  poweredBy: 'Propulsé par',
  reviewCta: 'Laissez-nous un avis Google',
  pickExactly: (n: number) => 'Choisissez {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'Au moins {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'Jusqu’à {n}'.replace('{n}', String(n)),
  optional: 'Facultatif',
  reviewHint: 'Vous avez aimé ? Votre avis nous aide énormément.',
  featured: 'Nos incontournables',
  from: 'dès',
  welcome: 'Bienvenue',
  tags: { popular: 'Populaire', spicy: 'Épicé', new: 'Nouveau', vegetarian: 'Végétarien' } as Record<string, string>,
  errors: {
    restaurant_not_found: 'Restaurant introuvable.',
    ordering_unavailable: 'La commande en ligne est indisponible pour le moment.',
    qr_ordering_off: 'Ce menu est à consulter : commandez auprès du serveur.',
    order_type_unavailable: 'Ce mode de commande n’est pas disponible.',
    invalid_table: 'Ce QR code de table n’est plus valide. Demandez au personnel.',
    customer_required: 'Merci d’indiquer votre prénom et votre téléphone.',
    item_unavailable: 'Un article n’est plus disponible, il a été retiré du panier.',
    item_sold_out: 'Un article est épuisé, il a été retiré du panier.',
    variant_required: 'Choisissez une option pour chaque article.',
    rate_limited: 'Trop de commandes en peu de temps. Réessayez dans quelques minutes.',
    invalid_request: 'La commande n’a pas pu être envoyée. Vérifiez votre panier.',
    network: 'Pas de connexion. Votre panier est conservé, réessayez.',
  } as Record<ErrorCode, string>,
};

type Strings = typeof fr;

const en: Strings = {
  ...fr,
  table: 'Table',
  search: 'Search the menu',
  searchClear: 'Clear',
  noResults: 'No results',
  soldOut: 'Sold out',
  add: 'Add',
  addToCart: 'Add',
  choose: 'Choose an option',
  quantity: 'Quantity',
  itemNote: 'Any special request? (no onions, well done...)',
  viewCart: 'View order',
  items: (n: number) => (n === 1 ? '1 item' : `${n} items`),
  cart: 'Your order',
  emptyCart: 'Your order is empty',
  orderNote: 'Note for the kitchen',
  orderNotePh: 'Allergies, special requests...',
  orderType: { dine_in: 'Dine in', takeaway: 'Takeaway', delivery: 'Delivery' },
  name: 'First name',
  phone: 'Phone',
  address: 'Delivery address',
  total: 'Total',
  placeOrder: 'Place order',
  sending: 'Sending...',
  scanTable: 'Scan the QR code on your table to order.',
  orderingOff: 'Online ordering is temporarily unavailable. You can still browse the menu.',
  browseOnly: 'Browse only',
  thanks: 'Thank you! Order received',
  ticket: 'Order',
  status: { new: 'Received', preparing: 'Preparing', ready: 'Ready', served: 'Served', cancelled: 'Cancelled' },
  statusHint: {
    new: 'The restaurant has received your order.',
    preparing: 'The kitchen is on it.',
    ready: 'Your order is ready.',
    served: 'Enjoy your meal!',
    cancelled: 'This order was cancelled. Please ask the staff.',
  },
  payAtCounter: 'Payment is handled by the staff.',
  backToMenu: 'Back to menu',
  trackOrder: 'Track',
  notFound: 'Restaurant not found',
  notFoundHint: 'Check the link or scan the QR code again.',
  retry: 'Try again',
  loadError: 'Could not load the menu.',
  close: 'Close',
  remove: 'Remove',
  poweredBy: 'Powered by',
  reviewCta: 'Leave us a Google review',
  pickExactly: (n: number) => 'Choose {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'At least {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'Up to {n}'.replace('{n}', String(n)),
  optional: 'Optional',
  reviewHint: 'Enjoyed it? Your review helps us a lot.',
  featured: 'Must try',
  from: 'from',
  welcome: 'Welcome',
  tags: { popular: 'Popular', spicy: 'Spicy', new: 'New', vegetarian: 'Vegetarian' },
  errors: {
    restaurant_not_found: 'Restaurant not found.',
    ordering_unavailable: 'Online ordering is unavailable right now.',
    qr_ordering_off: 'This menu is to read: please order with the staff.',
    order_type_unavailable: 'This order type is not available.',
    invalid_table: 'This table QR code is no longer valid. Please ask the staff.',
    customer_required: 'Please enter your first name and phone number.',
    item_unavailable: 'An item is no longer available and was removed from your order.',
    item_sold_out: 'An item is sold out and was removed from your order.',
    variant_required: 'Please choose an option for each item.',
    rate_limited: 'Too many orders in a short time. Please try again in a few minutes.',
    invalid_request: 'The order could not be sent. Please check your order.',
    network: 'No connection. Your order is kept, please try again.',
  },
};

const ar: Strings = {
  ...fr,
  table: 'الطاولة',
  search: 'ابحث في القائمة',
  searchClear: 'مسح',
  noResults: 'لا توجد نتائج',
  soldOut: 'نفد',
  add: 'أضف',
  addToCart: 'أضف',
  choose: 'اختر خيارا',
  quantity: 'الكمية',
  itemNote: 'طلب خاص؟ (بدون بصل، مطهو جيدا...)',
  viewCart: 'عرض الطلب',
  items: (n: number) => (n === 1 ? 'منتج واحد' : `${n} منتجات`),
  cart: 'طلبك',
  emptyCart: 'طلبك فارغ',
  orderNote: 'ملاحظة للمطبخ',
  orderNotePh: 'حساسية، طلبات خاصة...',
  orderType: { dine_in: 'في المطعم', takeaway: 'للأخذ', delivery: 'توصيل' },
  name: 'الاسم',
  phone: 'الهاتف',
  address: 'عنوان التوصيل',
  total: 'المجموع',
  placeOrder: 'اطلب الآن',
  sending: 'جار الإرسال...',
  scanTable: 'امسح رمز QR الموجود على طاولتك للطلب.',
  orderingOff: 'الطلب عبر الإنترنت غير متاح حاليا. يمكنك تصفح القائمة.',
  browseOnly: 'تصفح فقط',
  thanks: 'شكرا! تم استلام طلبك',
  ticket: 'الطلب',
  status: { new: 'تم الاستلام', preparing: 'قيد التحضير', ready: 'جاهز', served: 'تم التقديم', cancelled: 'ملغى' },
  statusHint: {
    new: 'تم استلام طلبك من طرف المطعم.',
    preparing: 'المطبخ يحضر طلبك.',
    ready: 'طلبك جاهز.',
    served: 'بالصحة والعافية!',
    cancelled: 'تم إلغاء هذا الطلب. يرجى التوجه إلى الموظفين.',
  },
  payAtCounter: 'الدفع يتم لدى الموظفين.',
  backToMenu: 'العودة إلى القائمة',
  trackOrder: 'تتبع',
  notFound: 'المطعم غير موجود',
  notFoundHint: 'تحقق من الرابط أو امسح رمز QR مرة أخرى.',
  retry: 'إعادة المحاولة',
  loadError: 'تعذر تحميل القائمة.',
  close: 'إغلاق',
  remove: 'حذف',
  poweredBy: 'بدعم من',
  reviewCta: 'اتركوا لنا رأيكم على Google',
  pickExactly: (n: number) => 'اختاروا {n}'.replace('{n}', String(n)),
  pickAtLeast: (n: number) => 'على الأقل {n}'.replace('{n}', String(n)),
  pickUpTo: (n: number) => 'حتى {n}'.replace('{n}', String(n)),
  optional: 'اختياري',
  reviewHint: 'أعجبكم؟ رأيكم يساعدنا كثيرا.',
  featured: 'الأكثر طلبا',
  from: 'ابتداء من',
  welcome: 'مرحبا بكم',
  tags: { popular: 'الأكثر طلبا', spicy: 'حار', new: 'جديد', vegetarian: 'نباتي' },
  errors: {
    restaurant_not_found: 'المطعم غير موجود.',
    ordering_unavailable: 'الطلب عبر الإنترنت غير متاح حاليا.',
    qr_ordering_off: 'هذه القائمة للاطلاع: اطلبوا من النادل.',
    order_type_unavailable: 'طريقة الطلب هذه غير متاحة.',
    invalid_table: 'رمز الطاولة لم يعد صالحا. يرجى سؤال الموظفين.',
    customer_required: 'يرجى إدخال الاسم ورقم الهاتف.',
    item_unavailable: 'منتج لم يعد متوفرا وتم حذفه من طلبك.',
    item_sold_out: 'منتج نفد وتم حذفه من طلبك.',
    variant_required: 'يرجى اختيار خيار لكل منتج.',
    rate_limited: 'طلبات كثيرة في وقت قصير. حاول بعد بضع دقائق.',
    invalid_request: 'تعذر إرسال الطلب. تحقق من طلبك.',
    network: 'لا يوجد اتصال. طلبك محفوظ، حاول مرة أخرى.',
  },
};

const ALL: Record<string, Strings> = { fr, en, ar };
export const strings = (lang: string): Strings => ALL[lang] ?? fr;
export const LANG_LABEL: Record<string, string> = { fr: 'FR', en: 'EN', ar: 'ع', es: 'ES' };
export type { Strings };
