/**
 * Converts the hardcoded Dom's Café menu (domscafe repo: src/data.ts +
 * initialCategories in src/firebase.ts) into SQL for the multi-tenant schema.
 * This is the migration path for tenant #1 (phase 3 of the plan), and it
 * gives local development a real, full menu.
 *
 * Usage:
 *   npx tsx scripts/import-domscafe.ts <path-to-domscafe-repo> [slug] > supabase/seed.sql
 *
 * Output is idempotent: ids are derived from the legacy ids, so running the
 * SQL twice updates instead of duplicating.
 *
 * NOT covered yet (do before the real switch-over):
 *   - live price/name overrides stored in Firestore (menuOverrides collection)
 *   - Firestore-only custom items (isCustom: true)
 *   Export those from Firestore and merge them in before running in production.
 */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const repo = resolve(process.argv[2] ?? '../domscafe');
const slug = process.argv[3] ?? 'doms-cafe';

type L = Record<string, string>;
interface LegacyVariant { id: string; name: L; price: number; image?: string }
interface LegacyItem {
  id: string; name: L; description: L; category: string; price: number; image: string;
  spicy?: boolean; popular?: boolean; available?: boolean; station?: string;
  variants?: LegacyVariant[]; fusion?: boolean;
}
interface LegacyCategory { id: string; name: L; emoji: string; displayOrder: number }

const { menuItems } = (await import(pathToFileURL(resolve(repo, 'src/data.ts')).href)) as { menuItems: LegacyItem[] };

// initialCategories lives in firebase.ts next to Firebase init code we must
// not execute, so extract the array literal and evaluate only that.
const fb = readFileSync(resolve(repo, 'src/firebase.ts'), 'utf8');
const m = fb.match(/export const initialCategories[^=]*=\s*(\[[\s\S]*?\n\]);/);
if (!m) throw new Error('initialCategories not found in firebase.ts');
const categories = (new Function(`return ${m[1]}`)() as LegacyCategory[]).filter(c => c.id !== 'all');

/** Stable UUID derived from a namespace + legacy id (same input, same id). */
function uid(kind: string, id: string): string {
  const h = createHash('sha1').update(`${slug}:${kind}:${id}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${((parseInt(h[16], 16) & 3) | 8).toString(16)}${h.slice(17, 20)}-${h.slice(20, 32)}`;
}
const q = (s: string | null | undefined) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const j = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;
const cents = (mad: number) => Math.round(mad * 100);
const i18n = (o: L | undefined) => Object.fromEntries(Object.entries(o ?? {}).filter(([, v]) => typeof v === 'string' && v.trim() !== ''));
const BAR = new Set(['boissons_chaudes', 'soda', 'jus_cocktails']);
const ORIGIN = 'https://domscafe.pages.dev';
const img = (p?: string) => (!p ? null : p.startsWith('http') ? p : ORIGIN + p);

const rid = uid('restaurant', slug);
const out: string[] = [];
out.push(`-- Generated by scripts/import-domscafe.ts from ${repo.split('/').pop()} on ${new Date().toISOString().slice(0, 10)}`);
out.push(`-- ${categories.length} categories, ${menuItems.length} items. Do not edit by hand, re-run the script.`);
out.push('begin;');
out.push(`insert into public.restaurants (id, slug, name, status, trial_ends_at, languages, address, city, branding,
  accept_dine_in, accept_takeaway, accept_delivery, opening_hours)
values ('${rid}', ${q(slug)}, 'Dom''s Café', 'active', null, '{fr,en,ar}', '26 rue Jabal Alayachi, Agdal', 'Rabat',
  ${j({ primary_color: '#C9A15A', theme: 'dark', logo_url: ORIGIN + '/logo.webp',
        tagline: { fr: 'Café & Restaurant', en: 'Café & Restaurant', ar: 'مقهى ومطعم' } })},
  true, true, false, ${j({ mon: [['08:00', '23:30']], tue: [['08:00', '23:30']], wed: [['08:00', '23:30']],
                           thu: [['08:00', '23:30']], fri: [['08:00', '23:30']], sat: [['08:00', '23:59']], sun: [['08:00', '23:59']] })})
on conflict (id) do update set name = excluded.name, branding = excluded.branding;`);

// 30 tables (as in the current Dom's till) with stable QR tokens
for (let t = 1; t <= 30; t++) {
  const token = uid('table', String(t)).replace(/-/g, '').slice(0, 10);
  out.push(`insert into public.dining_tables (id, restaurant_id, label, qr_token, sort_order) values ('${uid('table', String(t))}', '${rid}', '${t}', '${token}', ${t}) on conflict (id) do nothing;`);
}

const usedCats = new Set(menuItems.map(i => i.category));
for (const c of categories) {
  if (!usedCats.has(c.id)) continue;
  out.push(`insert into public.categories (id, restaurant_id, name, icon, station, sort_order)
values ('${uid('category', c.id)}', '${rid}', ${j(i18n(c.name))}, ${q(c.emoji)}, '${BAR.has(c.id) ? 'bar' : 'kitchen'}', ${Math.round(c.displayOrder * 10)})
on conflict (id) do update set name = excluded.name, icon = excluded.icon, sort_order = excluded.sort_order;`);
}
const knownCats = new Set(categories.map(c => c.id));
const orphans = [...usedCats].filter(c => !knownCats.has(c));
for (const c of orphans) {
  out.push(`insert into public.categories (id, restaurant_id, name, sort_order) values ('${uid('category', c)}', '${rid}', ${j({ fr: c })}, 999) on conflict (id) do nothing;`);
}

menuItems.forEach((it, idx) => {
  const tags = [it.popular && 'popular', it.spicy && 'spicy', it.fusion && 'new'].filter(Boolean) as string[];
  const station = it.station ? it.station.toLowerCase() : null;
  out.push(`insert into public.menu_items (id, restaurant_id, category_id, name, description, price_cents, image_url, station, tags, available, sort_order)
values ('${uid('item', it.id)}', '${rid}', '${uid('category', it.category)}', ${j(i18n(it.name))}, ${j(i18n(it.description))},
  ${cents(it.price)}, ${q(img(it.image))}, ${q(station)}, ${q(`{${tags.join(',')}}`)}, ${it.available === false ? 'false' : 'true'}, ${idx})
on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents,
  image_url = excluded.image_url, category_id = excluded.category_id, tags = excluded.tags, sort_order = excluded.sort_order;`);
  (it.variants ?? []).forEach((v, vi) => {
    out.push(`insert into public.item_variants (id, restaurant_id, menu_item_id, name, price_cents, sort_order)
values ('${uid('variant', it.id + '/' + v.id)}', '${rid}', '${uid('item', it.id)}', ${j(i18n(v.name))}, ${cents(v.price)}, ${vi})
on conflict (id) do update set name = excluded.name, price_cents = excluded.price_cents;`);
  });
});
out.push('commit;');
out.push(`-- QR link for table 1: https://${slug}.<your-domain>/t/${uid('table', '1').replace(/-/g, '').slice(0, 10)}`);
process.stdout.write(out.join('\n') + '\n');
process.stderr.write(`OK: ${categories.filter(c => usedCats.has(c.id)).length} categories, ${menuItems.length} items, ` +
  `${menuItems.reduce((n, i) => n + (i.variants?.length ?? 0), 0)} variants, orphan categories: ${orphans.join(',') || 'none'}\n`);
